### ISSUE TITLE
код стайл

### ISSUE THREAD

**Issue by vladimir-tl** [Dmytro-Mykhailenko/DimaMHomework3#1]
https://github.com/Dmytro-Mykhailenko/DimaMHomework3/blob/2e28c8f2c757eaabd00570e13b55be618a921b7c/src/Figure.java#L8

Добавление пустых строк в коде также может улучшить его читаемость и структурированность, особенно когда вы разделяете логические блоки кода или методы друг от друга. В Java принято использовать пустые строки для создания визуального разделения между различными частями кода.

**Comment by Dmytro-Mykhailenko** [comment]
ок, переделаю..
Нужно ли добавить перед каждым методом, описание вида  System.out.println("// Return Summ of Two Numbers"); ?

**Comment by vladimir-tl** [comment]
нет 
их названия должны говорить за себя
