### ISSUE TITLE
внутри уже не обязательно использовать //

### ISSUE THREAD

**Issue by vladimir-tl** [Dmytro-Mykhailenko/DimaMHomework3#2]
https://github.com/Dmytro-Mykhailenko/DimaMHomework3/blob/2e28c8f2c757eaabd00570e13b55be618a921b7c/src/Main.java#L15

**Comment by Dmytro-Mykhailenko** [comment]
Я так сделал чтобы было визуально сразу понятно какая часьть вывода в консоли к чему относится.. чобы легче читалось.

Если я перед каждым блоком добавлю перенос строки, так будет лучше?
System.out.println(); 
System.out.println("// Calculator");

**Comment by vladimir-tl** [comment]
как временное решение да - потом убрать
